version: '3.1'
services:
  server:
    image: node:alpine
    working_dir: /app
    ports:
      - '8001:8001'
    volumes:
      - ./:/app
    command:
      - 'npm ci'
      - 'npm run build'
      - 'node .'
    restart: always
